import { PieceColor, PieceType } from './shared-types';

export const BOARD_SIZE = 8;

export const CHESS_PIECES = [
  { type: PieceType.rook, color: PieceColor.white, position: 'a1' },
  { type: PieceType.knight, color: PieceColor.white, position: 'b1' },
  { type: PieceType.bishop, color: PieceColor.white, position: 'c1' },
  { type: PieceType.queen, color: PieceColor.white, position: 'd1' },
  { type: PieceType.king, color: PieceColor.white, position: 'e1' },
  { type: PieceType.bishop, color: PieceColor.white, position: 'f1' },
  { type: PieceType.knight, color: PieceColor.white, position: 'g1' },
  { type: PieceType.rook, color: PieceColor.white, position: 'h1' },
  { type: PieceType.pawn, color: PieceColor.white, position: 'a2' },
  { type: PieceType.pawn, color: PieceColor.white, position: 'b2' },
  { type: PieceType.pawn, color: PieceColor.white, position: 'c2' },
  { type: PieceType.pawn, color: PieceColor.white, position: 'd2' },
  { type: PieceType.pawn, color: PieceColor.white, position: 'e2' },
  { type: PieceType.pawn, color: PieceColor.white, position: 'f2' },
  { type: PieceType.pawn, color: PieceColor.white, position: 'g2' },
  { type: PieceType.pawn, color: PieceColor.white, position: 'h2' },
  { type: PieceType.rook, color: PieceColor.black, position: 'a8' },
  { type: PieceType.knight, color: PieceColor.black, position: 'b8' },
  { type: PieceType.bishop, color: PieceColor.black, position: 'c8' },
  { type: PieceType.queen, color: PieceColor.black, position: 'd8' },
  { type: PieceType.king, color: PieceColor.black, position: 'e8' },
  { type: PieceType.bishop, color: PieceColor.black, position: 'f8' },
  { type: PieceType.knight, color: PieceColor.black, position: 'g8' },
  { type: PieceType.rook, color: PieceColor.black, position: 'h8' },
  { type: PieceType.pawn, color: PieceColor.black, position: 'a7' },
  { type: PieceType.pawn, color: PieceColor.black, position: 'b7' },
  { type: PieceType.pawn, color: PieceColor.black, position: 'c7' },
  { type: PieceType.pawn, color: PieceColor.black, position: 'd7' },
  { type: PieceType.pawn, color: PieceColor.black, position: 'e7' },
  { type: PieceType.pawn, color: PieceColor.black, position: 'f7' },
  { type: PieceType.pawn, color: PieceColor.black, position: 'g7' },
  { type: PieceType.pawn, color: PieceColor.black, position: 'h7' },
];
